version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
